import { isValidId } from "../utils/validate-id";
import { idToComponentName } from "./to-jsx";

export interface RegistryGeneratorOptions {
	captureUrl?: string;
}

function generateMetaBlock(captureUrl: string): string {
	return `\nObject.defineProperty(registry, "__captureConfig__", {\n\tvalue: { url: ${JSON.stringify(captureUrl)} },\n\tenumerable: false,\n});\n`;
}

export function generateRegistry(
	ids: string[],
	options?: RegistryGeneratorOptions,
): string {
	const meta = options?.captureUrl ? generateMetaBlock(options.captureUrl) : "";

	for (const id of ids) {
		if (!isValidId(id)) {
			throw new Error(`Invalid skeleton id: "${id}"`);
		}
	}

	if (ids.length === 0) {
		return `// Auto-generated by autoskeleton — do not edit manually
import type { ComponentType } from "react";

export const registry: Record<string, ComponentType> = {};
${meta}`;
	}

	const imports = ids
		.map((id) => {
			const name = idToComponentName(id);
			return `import { ${name} } from "./${id}";`;
		})
		.join("\n");

	const entries = ids
		.map((id) => {
			const name = idToComponentName(id);
			return `\t"${id}": ${name},`;
		})
		.join("\n");

	return `// Auto-generated by autoskeleton — do not edit manually
import type { ComponentType } from "react";
${imports}

export const registry: Record<string, ComponentType> = {
${entries}
};
${meta}`;
}
